config/routes.rb
Rails.application.routes.draw do
  root        'kittens#index'
  resources   :kittens
end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @kittens }
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @kittens }
      format.json { render :json => @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:notice] = "You have successfully created a kitten"
      redirect_to @kitten
    else
      render 'new'
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      flash[:notice] = "You have successfully updated a kitten"
      redirect_to @kitten
    else
      render 'edit'
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash[:notice] = "You have successfully destroyed a kitten"
    redirect_to root_url
  end


  private

    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.erb
<%= form_for @kitten do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %></br>

  <%= f.label :age %>
  <%= f.number_field :age %></br>

  <%= f.label :cuteness %>
  <%= f.number_field :cuteness %></br>

  <%= f.label :softness %>
  <%= f.number_field :softness %></br>

  <%= f.submit "Submit" %>

<% end %>

app/views/kittens/edit.html.erb
<h1>Kittens#Edit</h1>

<p>Edit an existing kitten</p>

<%= render 'form' %>

<%= link_to 'Show', @kitten %> |
<%= link_to 'Back', kittens_path %>

app/views/kittens/index.html.erb
<h1>Kittens#Index</h1>

<div>
  <p>List of Kittens:</p>
  <% @kittens.each do |kitten| %>
    <ul>
      <li><%= kitten.name %></li>
      <li><%= link_to 'Destroy', kitten, method: :delete, data: { confirm: 'Are you sure?'} %></li>
    </ul>
<% end %>
</div>

<%= link_to 'New Kitten', new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Kittens#New</h1>

<p>Create a new kitten</p>

<%= render 'form' %>

<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<h1>Kittens#Show</h1>

<p>
  <strong>Name:</strong>
  <%= @kitten.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @kitten.age %>
</p>

<p>
  <strong>Softness:</strong>
  <%= @kitten.softness %>
</p>

<p>
  <strong>Cuteness:</strong>
  <%= @kitten.cuteness %>
</p>

<%= link_to 'Edit', edit_kitten_path(@kitten) %> |
<%= link_to 'Back', kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinKittens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<%= yield %>

</body>
</html>